	Introduction																				
	PT Jasintek Karya Abadi Inspector has carried out the crane inspection on October 08, 2025, at Workshop PT Widya Sentra Sarana - Jakarta Utara																				
																					
	Ref./ Code																				
	The inspection standard of crane according with Permen ESDM No. 32 Tahun 2021 ASME B30.5, ASME B 30.10, Hook and AWS D 14.3.																				
																					
	Scope																				
	In the inspections we have a step as follows : Document Review, Physical/Visual inspections, NDT magnetic test, Function test, Load test and reporting.																				
																					
	Document Review																				
	Reviewing process has been completely and suitable on each the technical specification, related document and supported document and then make sure with verification activity on the unit of equipment.																				
																					
	General Data Record																				
	Inspection activity on site the equipment was placed on a plain and firm ground, that has enough bearing capacity to safe operation, inspection and testing.																				
	The equipment is used for general lifting services, with the data are as follows :																				
	Crane			:	Rough Terrain Crane - Telescopic Boom							Owner			:	PT Total Crane					
	Serial No.			:	582006							User			:	PT Total Crane					
	Manufacturer			:	Tadano., Ltd. Kagawa-Japan							Capacity			:	50.0 Tons 					
	Model			:	TR-500M-3							Boom Installed			:	9.7 meter ~ 41.2 meter 					
	Year Built / Used			:	2018 / 2018																
																					
	Hoist Mechanism																				
	Hoisting mechanism with configuration a Boom, Hook Block assembly and wire rope for the load hoist and they are generated with hydraulic system.																				
																					
	Boom Hoist Mechanism																				
	Boom  configuration  are 6 section telescopic boom ( 1 base boom, 4 section boom, 1 top boom) without fly jib installed on main boom carrier. 																				
																					
	Traveling Mechanism																				
	Travelling mechanism of crane was generated with prime mover powered by diesel power engine.																				
																					
	Slewing Mechanism																				
	Slewing the boom are generated by hydraulic motor that attached on the chasis of the carrier, completed with swing lock.																				
																					
	Physical/Visual Inspections																				
	Physical inspections has performed on the over all structure component, rigging component, electric component, hydraulic component and mechanical component with visual examination.																				
	The Result of the inspection is not found the minor and major condition.																				
																					
	NDT/NDE Performed																				
	NDT Personnel Level 2 certified by SNT-TC-1A and NDT equipment has been reviewed and calibrated accordance with standard or code, NDT area was suitable with NDT Mapping.																				
	No significant indication was found during the test. See detail of  NDT Report.																				
																					
	Function  Test																				
	The Function test has been performed for all  mechanism, engine, safety devices and accessories as follows :																				
	- Boom Mechanism					(Up and Down/ Extended and Retracted of Boom)															
	- Load Hoist mechanism					(Up & Down of Load Block)															
	- Swing Mechanism																				
	- Emergency Shutdown																				
	- Safety Devices																				
	- Limits Switch																				
	There was not found any anomalies during the test. See detail of Function Test Record.																				
